# Preparation

## 设置CWD

In [1]:
import os
import sys
print(os.path.abspath(''))

workspace_path = os.path.abspath('')

# 去到最近的有.git的父目录
while not os.path.exists(os.path.join(workspace_path, '.git')):
    workspace_path = os.path.join(workspace_path, '..')
    if os.path.exists(os.path.join(workspace_path, '.git')):
        break

os.chdir(workspace_path)
print("current working directory: ", os.getcwd())
sys.path.append(os.path.join(workspace_path, 'src'))


/home/futou/projects/cumulonimbus/nimbus/src/experiments
current working directory:  /home/futou/projects/cumulonimbus/nimbus


## Load Data

In [2]:
import torch
# import modules
import numpy as np

checkpoint = torch.load('saves/model_checkpoints/Perceptron2-test_4/RsltChk-latest.pth')
weight = checkpoint['linear3.weight']

print(weight)

input = np.load('saves/input_cache/JBTest/input_nimbus_linear_2_latest.npy')
print(weight.shape, input.shape)

tensor([[ 3.7710e-41,  6.3988e-04,  8.2470e-01,  4.0351e-01, -1.5783e-01,
          2.6596e-01, -2.8826e-01,  9.2024e-04, -6.5420e-01, -6.0282e-01,
          2.4770e-01,  3.1837e-01,  3.4833e-01,  6.0645e-01,  1.6137e-01,
         -6.4354e-01,  4.5205e-01, -1.2689e-01, -5.5237e-01, -9.7803e-01,
          1.0098e+00,  9.8068e-02, -6.7403e-02,  3.8855e-20, -1.9476e-02,
          8.8891e-01,  3.1627e-01,  2.2169e-41, -7.6105e-01, -1.0805e-03,
          4.3923e-01,  4.0121e-41],
        [ 5.6914e-41, -8.7278e-05, -3.9147e-01, -5.5920e-01,  9.6399e-01,
          4.2181e-01,  6.6338e-01,  1.0713e-03,  1.1602e+00,  2.3408e-01,
         -1.1428e+00, -3.5919e-01, -1.4835e-02, -7.3594e-01, -6.7426e-01,
          3.3176e-01,  3.2221e-01, -6.1217e-01,  3.1218e-01,  3.5569e-01,
         -4.8062e-01,  2.2023e-01, -6.6901e-01,  1.5731e-23, -3.1300e-01,
         -8.2487e-01,  3.6663e-01, -2.4988e-41,  3.5329e-01, -6.2666e-03,
          2.2560e-01,  1.7837e-41],
        [ 6.2192e-41, -3.9210e-04, -4.91

In [3]:
import arg_settings
import modules

# create layer
layerJB = modules.NimbusLinearJoinedBucketing(32, 3, False, codeblockCount=16, treeDepth=4)
print(layerJB.weight)
layerJB.weight.data = weight

target min tensor(0) target max tensor(2)
start nimbus linear init, in_features: 14 out_features: 32 bias: False state: 1 codeblockCount: -1 treeDepth: 4
start nimbus linear init, in_features: 32 out_features: 32 bias: False state: 1 codeblockCount: -1 treeDepth: 4
start nimbus linear init, in_features: 32 out_features: 3 bias: False state: 1 codeblockCount: -1 treeDepth: 4
start nimbus linear init, in_features: 32 out_features: 3 bias: False state: 1 codeblockCount: 16 treeDepth: 4
Parameter containing:
tensor([[-0.0861,  0.0397, -0.0253, -0.1164,  0.0545, -0.0119, -0.0891, -0.1265,
          0.1373, -0.1693,  0.0258, -0.1384,  0.0781, -0.1726,  0.1323,  0.0948,
          0.0619, -0.0198, -0.0538,  0.1616,  0.0794, -0.1492,  0.0189,  0.0354,
         -0.0191,  0.1416, -0.0158, -0.0812, -0.1133, -0.1024, -0.0052,  0.0791],
        [ 0.0353,  0.0241,  0.0795, -0.0234,  0.1196,  0.1584, -0.1426,  0.0672,
          0.1580, -0.0660,  0.1501,  0.1284, -0.0501, -0.1739, -0.1447, -0.1625,
   

In [4]:
layerJB.weight

Parameter containing:
tensor([[ 3.7710e-41,  6.3988e-04,  8.2470e-01,  4.0351e-01, -1.5783e-01,
          2.6596e-01, -2.8826e-01,  9.2024e-04, -6.5420e-01, -6.0282e-01,
          2.4770e-01,  3.1837e-01,  3.4833e-01,  6.0645e-01,  1.6137e-01,
         -6.4354e-01,  4.5205e-01, -1.2689e-01, -5.5237e-01, -9.7803e-01,
          1.0098e+00,  9.8068e-02, -6.7403e-02,  3.8855e-20, -1.9476e-02,
          8.8891e-01,  3.1627e-01,  2.2169e-41, -7.6105e-01, -1.0805e-03,
          4.3923e-01,  4.0121e-41],
        [ 5.6914e-41, -8.7278e-05, -3.9147e-01, -5.5920e-01,  9.6399e-01,
          4.2181e-01,  6.6338e-01,  1.0713e-03,  1.1602e+00,  2.3408e-01,
         -1.1428e+00, -3.5919e-01, -1.4835e-02, -7.3594e-01, -6.7426e-01,
          3.3176e-01,  3.2221e-01, -6.1217e-01,  3.1218e-01,  3.5569e-01,
         -4.8062e-01,  2.2023e-01, -6.6901e-01,  1.5731e-23, -3.1300e-01,
         -8.2487e-01,  3.6663e-01, -2.4988e-41,  3.5329e-01, -6.2666e-03,
          2.2560e-01,  1.7837e-41],
        [ 6.2192e-

In [5]:
# 运行learn maddness joined，查看lut和simple lut avg的差别
layerJB.learn_maddness_params(input)

start split function with bucket_id:0, max_depth:4
bucket splitted with dim:1, threshold:0.5186643004417419, from bucket_id:0's shape (406536, 2), to bucket id 1 with length (298669, 2) & bucket id 2 with length (107867, 2)
start split function with bucket_id:1, max_depth:3
bucket splitted with dim:1, threshold:0.17207971215248108, from bucket_id:1's shape (298669, 2), to bucket id 3 with length (259415, 2) & bucket id 4 with length (39254, 2)
start split function with bucket_id:3, max_depth:2
bucket splitted with dim:1, threshold:0.056539520621299744, from bucket_id:3's shape (259415, 2), to bucket id 7 with length (237404, 2) & bucket id 8 with length (22011, 2)
start split function with bucket_id:7, max_depth:1
bucket splitted with dim:1, threshold:0.01841186359524727, from bucket_id:7's shape (237404, 2), to bucket id 15 with length (230545, 2) & bucket id 16 with length (6859, 2)
start split function with bucket_id:15, max_depth:0
start split function with bucket_id:16, max_depth:

In [6]:
inputTensor = torch.from_numpy(input).float().to(arg_settings.Device)
# inputTensor = inputTensor[:100]
layerJB.compare_outputs(inputTensor)

NMSE between matmul and dm for nimbus_linear_3: 0.020570790395140648
NMSE between matmul and maddness for nimbus_linear_3: 0.020570790395140648


In [7]:
nimbusLinear = modules.NimbusLinear(32, 3, False, codeblockCount=16, treeDepth=4)
nimbusLinear.weight.data = weight
nimbusLinear.learn_maddness_params(input)
nimbusLinear.compare_outputs(inputTensor)

start nimbus linear init, in_features: 32 out_features: 3 bias: False state: 1 codeblockCount: 16 treeDepth: 4
Learning progress (406536, 32)-16-16: 1/16 (2.707 GB)
Learning progress (406536, 32)-16-16: 2/16 (2.721 GB)
Learning progress (406536, 32)-16-16: 3/16 (2.721 GB)
Learning progress (406536, 32)-16-16: 4/16 (2.721 GB)
Learning progress (406536, 32)-16-16: 5/16 (2.721 GB)
Learning progress (406536, 32)-16-16: 6/16 (2.744 GB)
Learning progress (406536, 32)-16-16: 7/16 (2.744 GB)
Learning progress (406536, 32)-16-16: 8/16 (2.744 GB)
Learning progress (406536, 32)-16-16: 9/16 (2.744 GB)
Learning progress (406536, 32)-16-16: 10/16 (2.744 GB)
Learning progress (406536, 32)-16-16: 11/16 (2.744 GB)
Learning progress (406536, 32)-16-16: 12/16 (2.744 GB)
Learning progress (406536, 32)-16-16: 13/16 (2.744 GB)
Learning progress (406536, 32)-16-16: 14/16 (2.744 GB)
Learning progress (406536, 32)-16-16: 15/16 (2.744 GB)
Learning progress (406536, 32)-16-16: 16/16 (2.752 GB)
X_error mse / X me

## 使用linear2进行测试

In [2]:
import torch
# import modules
import numpy as np

checkpoint = torch.load('saves/model_checkpoints/Perceptron2-test_4/RsltChk-latest.pth')
weight = checkpoint['linear2.weight']

print(weight)

input = np.load('saves/input_cache/JBTest/input_nimbus_linear_1_latest.npy')
print(weight.shape, input.shape)

tensor([[-3.8346e-03,  2.8145e-03,  9.4741e-05,  ..., -2.7275e-03,
         -9.2908e-04,  5.2954e-03],
        [ 1.0195e-01, -1.0506e-01,  1.1463e-01,  ...,  5.9740e-03,
          1.0336e-02, -3.8525e-02],
        [ 2.0678e-01, -1.1549e-01,  6.2614e-02,  ..., -8.4248e-04,
          2.6372e-03, -5.8528e-02],
        ...,
        [-1.4125e-02,  3.4981e-02, -5.1187e-02,  ..., -5.8306e-02,
         -6.8344e-04,  1.1636e-01],
        [ 1.1201e-01, -8.8166e-02,  9.1975e-02,  ..., -3.4728e-02,
          1.8281e-01,  3.0451e-02],
        [ 3.6090e-41, -7.0372e-41, -6.6595e-41,  ...,  8.8394e-42,
         -1.6170e-41,  3.6678e-41]], device='cuda:0')
torch.Size([32, 32]) (406536, 32)


In [5]:
import arg_settings
import modules

# create layer
layerJB = modules.NimbusLinearJoinedBucketing(32, 32, False, codeblockCount=16, treeDepth=4)
layerJB.weight.data = weight
print(layerJB.weight)


start nimbus linear init, in_features: 32 out_features: 32 bias: False state: 1 codeblockCount: 16 treeDepth: 4
Parameter containing:
tensor([[-3.8346e-03,  2.8145e-03,  9.4741e-05,  ..., -2.7275e-03,
         -9.2908e-04,  5.2954e-03],
        [ 1.0195e-01, -1.0506e-01,  1.1463e-01,  ...,  5.9740e-03,
          1.0336e-02, -3.8525e-02],
        [ 2.0678e-01, -1.1549e-01,  6.2614e-02,  ..., -8.4248e-04,
          2.6372e-03, -5.8528e-02],
        ...,
        [-1.4125e-02,  3.4981e-02, -5.1187e-02,  ..., -5.8306e-02,
         -6.8344e-04,  1.1636e-01],
        [ 1.1201e-01, -8.8166e-02,  9.1975e-02,  ..., -3.4728e-02,
          1.8281e-01,  3.0451e-02],
        [ 3.6090e-41, -7.0372e-41, -6.6595e-41,  ...,  8.8394e-42,
         -1.6170e-41,  3.6678e-41]], device='cuda:0', requires_grad=True)


In [6]:
# 运行learn maddness joined，查看lut和simple lut avg的差别
layerJB.learn_maddness_params(input)

start split function with bucket_id:0, max_depth:4
bucket splitted with dim:1, threshold:0.17782554030418396, from bucket_id:0's shape (406536, 2), to bucket id 1 with length (243172, 2) & bucket id 2 with length (163364, 2)
start split function with bucket_id:1, max_depth:3
bucket splitted with dim:0, threshold:0.3234568238258362, from bucket_id:1's shape (243172, 2), to bucket id 3 with length (235974, 2) & bucket id 4 with length (7198, 2)
start split function with bucket_id:3, max_depth:2
bucket splitted with dim:0, threshold:0.0666123479604721, from bucket_id:3's shape (235974, 2), to bucket id 7 with length (200259, 2) & bucket id 8 with length (35715, 2)
start split function with bucket_id:7, max_depth:1
bucket splitted with dim:1, threshold:0.05257704108953476, from bucket_id:7's shape (200259, 2), to bucket id 15 with length (183792, 2) & bucket id 16 with length (16467, 2)
start split function with bucket_id:15, max_depth:0
start split function with bucket_id:16, max_depth:0


In [7]:
inputTensor = torch.from_numpy(input).float().to(arg_settings.Device)
# inputTensor = inputTensor[:100]
layerJB.compare_outputs(inputTensor)

NMSE between matmul and dm for nimbus_linear_5: 0.01741611771285534
NMSE between matmul and maddness for nimbus_linear_5: 0.01741611771285534


In [8]:
nimbusLinear = modules.NimbusLinear(32, 32, False, codeblockCount=16, treeDepth=4)
nimbusLinear.weight.data = weight
nimbusLinear.learn_maddness_params(input)
nimbusLinear.compare_outputs(inputTensor)

start nimbus linear init, in_features: 32 out_features: 32 bias: False state: 1 codeblockCount: 16 treeDepth: 4
Learning progress (406536, 32)-16-16: 1/16 (2.725 GB)
Learning progress (406536, 32)-16-16: 2/16 (2.730 GB)
Learning progress (406536, 32)-16-16: 3/16 (2.733 GB)
Learning progress (406536, 32)-16-16: 4/16 (2.733 GB)
Learning progress (406536, 32)-16-16: 5/16 (2.733 GB)
Learning progress (406536, 32)-16-16: 6/16 (2.733 GB)
Learning progress (406536, 32)-16-16: 7/16 (2.733 GB)
Learning progress (406536, 32)-16-16: 8/16 (2.743 GB)
Learning progress (406536, 32)-16-16: 9/16 (2.743 GB)
Learning progress (406536, 32)-16-16: 10/16 (2.743 GB)
Learning progress (406536, 32)-16-16: 11/16 (2.745 GB)
Learning progress (406536, 32)-16-16: 12/16 (2.752 GB)
Learning progress (406536, 32)-16-16: 13/16 (2.752 GB)
Learning progress (406536, 32)-16-16: 14/16 (2.760 GB)
Learning progress (406536, 32)-16-16: 15/16 (2.761 GB)
Learning progress (406536, 32)-16-16: 16/16 (2.793 GB)
X_error mse / X m